apiVersion: v1
kind: Template
labels:
  app: drupal8-php-fpm-mysql-nginx
  template: drupal8-php-fpm-mysql-nginx
metadata:
   name: "Drupal8-fpm-mysql-nginx"
   namespace: production-cloud
   annotations:
      description: An example drupal8 application with a MySQL database.
      iconClass: "icon-php"
      tags: quickstart,php-fpm,drupal8,mysql,nginx
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name:  dbsecret
      stringData:
        "MYSQL_USER": "${MYSQL_USER}"
        "MYSQL_PASSWORD": "${MYSQL_PASSWORD}"
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata: 
      name: drupal-pvc
      namespace: production-cloud
    spec: 
      accessModes: 
        - ReadWriteOnce
      resources: 
        requests: 
          storage: 5Gi
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata: 
      name: drupal-pvc-mysql
      namespace: production-cloud
    spec: 
      accessModes: 
        - ReadWriteOnce
      resources: 
        requests: 
          storage: 5Gi
  # - apiVersion: v1
  #   kind: Pod
  #   metadata:
  #     name: mysql-master
  #     namespace: production-cloud
  #   spec:
  #     containers:
  #       - env:
  #         # - name: "MYSQL_MASTER_USER"
  #         #   value: "${MYSQL_MASTER_USER}"
  #         # - name: "MYSQL_MASTER_PASSWORD"
  #         #   value: "${MYSQL_MASTER_PASSWORD}"
  #         - name: "MYSQL_USER"
  #           value: "${MYSQL_USER}"
  #         - name: "MYSQL_PASSWORD"
  #           value: "${MYSQL_PASSWORD}"
  #         - name: "MYSQL_DATABASE"
  #           value: "${MYSQL_DATABASE}"
  #         # - name: "MYSQL_ROOT_PASSWORD"
  #         #   value: "${MYSQL_ROOT_PASSWORD}"
  #         # image: <Image Name>
  #         image: centos/mysql-57-centos7:latest
  #         name: "mysql"
  #         ports:
  #           # - containerPort: <Container port number>
  #           #    protocol: <Protocol>
  #           - containerPort: 3306
  #             protocol: TCP
  #   labels:
  #     #  redis: <Communication Type>
  #     mysql: master
  # - apiVersion: v1
  #   kind: Pod
  #   metadata:
  #     name: mysql-slave
  #     namespace: production-cloud
  #   spec:
  #     containers:
  #       - env:
  #         # - name: "MYSQL_MASTER_USER"
  #         #   value: "${MYSQL_MASTER_USER}"
  #         # - name: "MYSQL_MASTER_PASSWORD"
  #         #   value: "${MYSQL_MASTER_PASSWORD}"
  #         - name: "MYSQL_USER"
  #           value: "${MYSQL_USER}"
  #         - name: "MYSQL_PASSWORD"
  #           value: "${MYSQL_PASSWORD}"
  #         - name: "MYSQL_DATABASE"
  #           value: "${MYSQL_DATABASE}"
  #         # - name: "MYSQL_ROOT_PASSWORD"
  #         #   value: "${MYSQL_ROOT_PASSWORD}"
  #         # image: <Image Name>
  #         image: centos/mysql-57-centos7:latest
  #         name: "mysql"
  #         ports:
  #           # - containerPort: <Container port number>
  #           #    protocol: <Protocol>
  #           - containerPort: 3306
  #             protocol: TCP
  #   labels:
  #     #  redis: <Communication Type>
  #     mysql: slave
  # - apiVersion: v1
  #   kind: Pod
  #   metadata:
  #     name: drupal8-fpm
  #     namespace: production-cloud
  #   spec:
  #     containers:
  #       - 
  #         image: drupal:8.6.7-fpm
  #         # image: zevgenz/drupal-cfg
  #         name: drupal-fpm
  #         ports:
  #             - containerPort: 9000
  #               protocol: TCP
  #   labels:
  #     #  redis: <Communication Type>
  #     drupal: drupal-fpm
  # - apiVersion: v1
  #   kind: Pod
  #   metadata:
  #     name: nginx
  #     namespace: production-cloud
  #   spec:
  #     containers:
  #       - env:
  #         - name: SERVERNAME
  #           # value: "${SERVERNAME}"
  #           value: drupal8-fpm
  #         image: zevgenz/nginx-cfg:latest
  #         name: nginx
  #         ports:
  #           - containerPort: 8081
  #             protocol: TCP
  #   labels:
  #     #  redis: <Communication Type>
  #     nginx: nginx
  - apiVersion: v1
    kind: Service
    metadata:
      name:  drupal-fpm-service
      namespace: production-cloud
      creationTimestamp: null
    spec:
      selector:
        # app:  Selector Label
        app: drupal-fpm-service
        tier: backend
      # portalIP: ""
      # type:  ClusterIP
      # sessionAffinity: None
      ports:
      - name:  fpm
        port:  9000
        protocol: TCP
        targetPort:  fpm
        # nodePort: 0
  - apiVersion: v1
    kind: Service
    metadata:
      name:  mysql-service
      namespace: production-cloud
      creationTimestamp: null
    spec:
      selector:
        # app:  Selector Label
        app: mysql-service
      # type:  ClusterIP
      # sessionAffinity: None
      ports:
      - name:  mysql
        port:  3306
        protocol: TCP
        # targetPort:  drupal8-db
        # nodePort: 0
  - apiVersion: v1
    kind: Service
    metadata:
      name:  nginx-service
      namespace: production-cloud
      creationTimestamp: null
    spec:
      selector:
        # app:  Selector Label
        app: nginx
      type: LoadBalancer
      # portalIP: ""
      # type:  ClusterIP
      # sessionAffinity: None
      ports:
      - name:  nginx
        port:  8081
        protocol: TCP
        # targetPort:  8081
        # nodePort: 0
    # status: 
    #   loadBalancer: ""
  - apiVersion: v1
    kind: Route
    metadata:
      name: nginx-service
      namespace: production-cloud
      creationTimestamp: null
    spec:
      to:
        kind: Service
        name: nginx-service
    port:
      targetPort: nginx
      # tls: edge
      insecureEdgeTerminationPolicy: Allow
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata: 
      # labels:
      matchLabels: 
        app: drupal8-fpm
        tier: backend
        track: stable
      name: drupal8-fpm
      namespace: production-cloud
    spec: 
      replicas: 1
      template: 
        metadata: 
          labels: 
            app: drupal8-fpm
            tier: backend
            track: stable
        spec: 
          initContainers:
            -
              name: init-sites-volume
              image: drupal:8.6.7-fpm
              # image: zevgenz/drupal-cfg
              command: ['/bin/bash', '-c']
              # args: ['cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R']
              args: ['cp -r /var/www/html/ /data/; chown www-data:www-data /data/ -R; cp ./sites/default/default.settings.php ./sites/default/settings.php']
              volumeMounts:
              - mountPath: /data
                name: vol-drupal
          containers: 
            - 
              image: drupal:8.6.7-fpm
              # image: zevgenz/drupal-cfg
              name: drupal8-fpm
              ports: 
                - 
                  name: fpm
                  containerPort: 9000
              volumeMounts:
              - mountPath: /var/www/html/modules
                name: vol-drupal
                subPath: modules
              - mountPath: /var/www/html/profiles
                name: vol-drupal
                subPath: profiles
              - mountPath: /var/www/html/sites
                name: vol-drupal
                subPath: sites
              - mountPath: /var/www/html/themes
                name: vol-drupal
                subPath: themes
          volumes:
            - 
              name: vol-drupal
              persistentVolumeClaim: 
                claimName: drupal-pvc
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata: 
      name: mysql-master
      namespace: production-cloud
    spec: 
      replicas: 1
      template: 
        metadata: 
          labels: 
            app: mysql-master
        spec: 
          containers: 
            - 
              env: 
                - 
                  name: MYSQL_ROOT_PASSWORD
                  value: ${MYSQL_ROOT_PASSWORD}
                # - 
                #   name: MYSQL_DATABASE
                #   value: drupal-database
                - 
                  name: MYSQL_USER
                  value: ${MYSQL_USER}
                - 
                  name: MYSQL_PASSWORD
                  value: ${MYSQL_PASSWORD}
                - 
                  name: MYSQL_DATABASE
                  value: ${MYSQL_DATABASE}
              image: "mysql:5.7"
              # name: cont-drupal-mysql
              name: mysql-master
              ports: 
                - 
                  containerPort: 3306
                  name: mysql
                  protocol: TCP
              volumeMounts: 
                - 
                  mountPath: /var/lib/mysql
                  name: vol-drupal
                  subPath: dbdata
          volumes: 
            - 
              name: vol-drupal
              persistentVolumeClaim: 
                claimName: drupal-pvc-mysql
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata: 
      labels: 
        app: nginx
      name: nginx
      namespace: production-cloud
    spec: 
      replicas: 1
      template: 
        metadata: 
          labels: 
            app: nginx
        spec: 
          initContainers:
            -
              name: init-nginx
              image: zevgenz/nginx-cfg:latest
              command: ['/bin/bash', '-c']
              args: ['chmod g+rwx /var/cache/nginx /var/run /var/log/nginx']
              # volumeMounts:
              # - mountPath: /data
              #   name: vol-drupal
          containers: 
            - 
              image: zevgenz/nginx-cfg:latest
              name: nginx
              ports: 
                - 
                  containerPort: 8081
              # volumeMounts:
              # - mountPath: /var/www/html
              #   name: vol-drupal
              # - mountPath: /var/www/html/modules
              #   name: vol-drupal
              #   subPath: modules
              # - mountPath: /var/www/html/profiles
              #   name: vol-drupal
              #   subPath: profiles
              # - mountPath: /var/www/html/sites
              #   name: vol-drupal
              #   subPath: sites
              # - mountPath: /var/www/html/themes
              #   name: vol-drupal
              #   subPath: themes
          # volumes:
          #   - 
          #     name: vol-drupal
          #     persistentVolumeClaim: 
          #       claimName: drupal-pvc
restartPolicy: "Always"
dnsPolicy: "ClusterFirst"
